import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/",headers:{
        'api-key': '9cc584e7-e30a-4c86-a83b-87222be5dc3c'
    } });